JhonyDomingos/backend-just-connect

- README.md
- package.json
- src/prisma/index.ts
- src/server.ts
> Chore: adding scripts on package.json

- prisma/schema.prisma
Criação das tabelas do banco de dados no arquivo do schema.prisma.
Não consegui atualizar o arquivo do migartion.sql, porém no prisma studio apareciam as novas tabelas.
...
- N/A
This pull request has dependencies on the following others: none
- N/A
> Feat: Create os database tables

- .idea/.gitignore
- .idea/aws.xml
- .idea/backend-just-connect.iml
- .idea/modules.xml
- .idea/vcs.xml
- package-lock.json
- package.json
- src/@types/express/index.d.ts
- src/controllers/auth/AuthController.ts
- src/controllers/user/CreateUserController.ts
- src/controllers/user/DeleteUserController.ts
- src/controllers/user/EditUserController.ts
- src/controllers/user/FindAllUserController.ts
- src/controllers/user/FindUserController.ts
- src/interfaces/auth/Payload.ts
- src/interfaces/auth/authRequest.ts
- src/interfaces/user/UserRequest.ts
- src/middlewares/auth/isAuthenticated.ts
- src/prisma/index.ts
- src/routes.ts
- src/server.ts
- src/services/auth/AuthService.ts
- src/services/user/CreateUserService.ts
- src/services/user/DeleteUserService.ts
- src/services/user/EditUserService.ts
- src/services/user/FindAllUserService.ts
- src/services/user/FindUserService.ts
- tsconfig.json
Creation of Service, Controller, Interface of User.
...
> Feat: Service, Controller an Interface of User

- package-lock.json
- package.json
- src/server.ts
- src/swagger.ts
- swagger_output.json
> Feat: Configuring and Adding the Swagger Documentation

- prisma/migrations/20241024162324_refactor_attribute_name/migration.sql
- prisma/migrations/20241024163310_refactor_user_role/migration.sql
- prisma/migrations/20241024174816_refactor_created_updated_names/migration.sql
- prisma/schema.prisma
1. Changing attribute names to snake case in database [old (**new**)]:
- _user_: createdAt (**created_at**), updatedAt (**updated_at**);
- _post_: userId (**user_id**), postCreatedAt (**created_at**), postUpdatedAt (**updated_at**), adminPostBlock (**admin_post_block**);
- _comment_: userId (**user_id**), postId (**post_id**), commentCreatedAt (**created_at**), commentUpdatedAt (**updated_at**), adminCommentBlock (**admin_comment_block**);
2. Character limitation in **name** attribute in _user_: **VARCHAR(100)**;
3. Inclusion of enum in the **role** attribute in _user_;
4. Removing comments in code.
...
- N/A
- N/A
> Refactor: Changes to schema.prisma

- src/interfaces/post/ICreateTag.ts
- src/services/post/CreateTagService.ts
> Feat: Tags

- src/controllers/comments/CreateCommentController.ts
- src/interfaces/comments/CommentsType.ts
- src/interfaces/comments/IComment.ts
- src/routes/index.routes.ts
- src/routes/private/comment.private.routes.ts
- src/schemas/commentSchemas.ts
- src/services/comments/CreateCommentService.ts
...
...
- Create Comments
- [x ] My changes are 400 lines or less
- [x ] I have performed a self-review of my own code
> Feat: Create Comments Interface, Service, Controller and Routes

- src/controllers/comments/DeleteCommentController.ts
- src/routes/private/comment.private.routes.ts
- src/schemas/commentSchemas.ts
- src/services/comments/CreateCommentService.ts
- src/services/comments/DeleteCommentService.ts
...
...
- Delete comments in post.
> Feat: Delete Comment Service Created

- src/controllers/comments/FindAllCommentController.ts
- src/interfaces/comments/CommentsType.ts
- src/routes/private/comment.private.routes.ts
- src/services/comments/FindAllCommentService.ts
...
...
- Review code of comments
> Fix: Review Code FindAllCommentsService and Controller.

- src/controllers/tag/CreateTagController.ts
- src/interfaces/tag/ITag.ts
- src/routes/index.routes.ts
- src/routes/private/tag.private.routes.ts
- src/services/tag/CreateTagService.ts
...
...
- Feat: Create Tag Service, Controller and Route
> Feat: Create Tag Service, Controller and Route

- src/controllers/comments/UpdateCommentController.ts
- src/interfaces/comments/CommentsType.ts
- src/routes/private/comment.private.routes.ts
- src/schemas/commentSchemas.ts
- src/services/comments/UpdateCommentService.ts
...
...
- [Created UpdateComments Service and Controller.
> Feat: UpdateComment Service and Controller

- prisma/migrations/20241102013412_refactor_relations_ondelete/migration.sql
- prisma/schema.prisma
Update relationships in database with constraint ON DELETE CASCADE
...
- N/A
- N/A
> Refactor: Database update relationships with ON DELETE CASCADE

- prisma/migrations/20241110010814_refactor_general_attibutes/migration.sql
- prisma/migrations/20241110011036_create_enum_typereports/migration.sql
- prisma/migrations/20241110011631_create_postreport/migration.sql
- prisma/migrations/20241110012026_create_commentreport/migration.sql
- prisma/migrations/20241110012400_create_postlike/migration.sql
- prisma/migrations/20241110012933_create_commentlike/migration.sql
- prisma/schema.prisma
Feat: create tables PostReport, CommentReport, PostLike and CommentLike
Refactor: adjustment in some attributes. Comments in the code
...
- N/A
- N/A
> Feat: create tables PostReport, CommentReport, PostLike and CommentLike

- .env-example
> Feat: Created .env-example

- prisma/migrations/20241114200913_create_taglike_table/migration.sql
- prisma/migrations/20241114203434_refactor_tagfollow_table/migration.sql
- prisma/schema.prisma
Feature: create TAGLIKE table in database
...
- N/A
- N/A
> Feature: create TAGLIKE table

- src/controllers/search/SearchController.ts
- src/interfaces/tag/TagTypes.ts
- src/schemas/tagSchemas.ts
- src/services/search/SearchService.ts
Adding Search Tags Function inside the search service.
...
> Feat: Adding Search tags function

- src/controllers/post/LikePostController.ts
- src/interfaces/post/PostType.ts
- src/routes/private/post.private.routes.ts
- src/schemas/postSchemas.ts
- src/services/post/LikePostService.ts
> Feat: Created Like Post Service

- src/controllers/post/LikePostController.ts
- src/routes/private/post.private.routes.ts
- src/services/post/LikePostService.ts
> Fix: Changing the term unlike for dislike

- src/controllers/tag/ListTagsController.ts
- src/controllers/tag/TagFollowController.ts
- src/controllers/tag/TagFollowStatusController.ts
- src/interfaces/tag/TagTypes.ts
- src/routes/index.routes.ts
- src/routes/private/tag.private.routes.ts
- src/routes/public/post.public.routes.ts
- src/routes/public/tag.public.routes.ts
- src/routes/public/user.public.routes.ts
- src/schemas/tagSchemas.ts
- src/services/tag/FollowTagService.ts
- src/services/tag/ListTagsService.ts
- src/services/tag/TagFollowService.ts
- src/services/tag/TagFollowStatusService.ts
- src/services/tag/UnfollowTagService.ts
- swagger_output.json
- follow tags
- follow tags status
- list tags
- fix middleware
...
...
> feat: follow tags, list tags

- docker-compose.yml
- src/middlewares/ensure/ensure.middleware.ts
- src/routes/public/user.public.routes.ts
- src/services/user/GetUserByUsernameService.ts
> Refacotr: refactor middleware and removing unused verification

- src/routes/private/user.private.routes.ts
> Refactor: Removing middleware and change to PATCH to put

- .gitignore
- package-lock.json
- package.json
- src/controllers/post/DeletePostController.ts
- src/controllers/post/UpdatePostController.ts
- tsconfig.json
- vercel.json
> Feat: Created the Deploy service

- docker-compose.yml
- prisma/migrations/20241125173247_add_notifications_table/migration.sql
- prisma/schema.prisma
- src/controllers/comments/LikeCommentController.ts
- src/controllers/notifications/NotificationController.ts
- src/controllers/post/LikePostController.ts
- src/interfaces/notification/CreateNotification.ts
- src/routes/index.routes.ts
- src/routes/private/comment.private.routes.ts
- src/routes/private/notification.private.routes.ts
- src/routes/private/post.private.routes.ts
- src/server.ts
- src/services/comments/CreateCommentService.ts
- src/services/comments/LikeCommentService.ts
- src/services/notifications/NotificationService.ts
- src/services/post/LikePostService.ts
- swagger_output.json
- adjusts on likes
- initial config for notifications
...
> feat: likes routes adjustments and initial config for notifications

- src/schemas/commentSchemas.ts
- src/services/post/FindOnePostService.ts
> refactor: comments on posts return

- src/controllers/tag/GetFollowedTagsPostsController.ts
- src/routes/private/tag.private.routes.ts
- src/services/tag/GetFollowedTagsPostsService.ts
- swagger_output.json
- listing posts with tags followed by logged user
...
> feat: get posts with tags followed by user

- src/controllers/tag/GetFollowedTagsPostsController.ts
- src/routes/private/tag.private.routes.ts
- src/routes/private/user.private.routes.ts
- src/services/tag/GetFollowedTagsPostsService.ts
- swagger_output.json
> refactor: put to patch

- src/services/comments/CreateCommentService.ts
- src/services/comments/LikeCommentService.ts
- src/services/post/LikePostService.ts
> fix: username notification
